<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
require dirname(__DIR__).'/app/bootstrap.php';
use App\Controllers\AuthController;use App\Controllers\DashboardController;use App\Controllers\EmployeeController;use App\Controllers\EventController;use App\Controllers\ScannerController;use App\Controllers\SouvenirController;use App\Controllers\ReportController;use App\Controllers\UserController;use App\Controllers\ProfileController;
$uri=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH)??'/';$base=rtrim(dirname($_SERVER['SCRIPT_NAME']),'/');if($base&&str_starts_with($uri,$base))$uri=substr($uri,strlen($base));$uri='/'.trim($uri,'/');
if($uri===''||$uri==='/')redirect(\App\Auth::check()?\App\Auth::home():'/login');
elseif($uri==='/login')AuthController::login();elseif($uri==='/logout')AuthController::logout();
elseif($uri==='/dashboard')DashboardController::index();elseif(preg_match('#^/dashboard/export/([a-z]+)$#',$uri,$m))DashboardController::exportCard($m[1]);
elseif($uri==='/profile')ProfileController::index();
elseif($uri==='/users')UserController::index();elseif($uri==='/users/create')UserController::form();elseif(preg_match('#^/users/(\d+)/edit$#',$uri,$m))UserController::form((int)$m[1]);elseif(preg_match('#^/users/(\d+)/delete$#',$uri,$m))UserController::delete((int)$m[1]);
elseif($uri==='/employees')EmployeeController::index();elseif($uri==='/employees/create')EmployeeController::form();elseif(preg_match('#^/employees/(\d+)/edit$#',$uri,$m))EmployeeController::form((int)$m[1]);elseif(preg_match('#^/employees/(\d+)/delete$#',$uri,$m))EmployeeController::delete((int)$m[1]);elseif($uri==='/employees/bulk-delete')EmployeeController::bulkDelete();elseif($uri==='/employees/import')EmployeeController::import();elseif($uri==='/employees/import/template')EmployeeController::importTemplate();
elseif($uri==='/events')EventController::index();elseif($uri==='/events/create')EventController::form();elseif($uri==='/events/bulk-delete')EventController::bulkDelete();elseif(preg_match('#^/events/(\d+)/edit$#',$uri,$m))EventController::form((int)$m[1]);elseif(preg_match('#^/events/(\d+)/delete$#',$uri,$m))EventController::delete((int)$m[1]);elseif(preg_match('#^/events/(\d+)/invitations$#',$uri,$m))EventController::invitations((int)$m[1]);elseif(preg_match('#^/events/(\d+)/invitations/add$#',$uri,$m))EventController::addInvitations((int)$m[1]);elseif(preg_match('#^/events/(\d+)/invitations/generate-qr$#',$uri,$m))EventController::generateAllQr((int)$m[1]);elseif(preg_match('#^/events/(\d+)/invitations/send-all$#',$uri,$m))EventController::sendAll((int)$m[1]);elseif(preg_match('#^/events/(\d+)/invitations/send-batch$#',$uri,$m))EventController::sendBatch((int)$m[1]);elseif(preg_match('#^/events/(\d+)/invitations/(\d+)/qr\.png$#',$uri,$m))EventController::qrImage((int)$m[1],(int)$m[2]);elseif(preg_match('#^/events/(\d+)/invitations/remove$#',$uri,$m))EventController::removeInvitations((int)$m[1]);elseif(preg_match('#^/events/(\d+)/souvenirs$#',$uri,$m))SouvenirController::allocate((int)$m[1]);
elseif($uri==='/souvenirs')SouvenirController::index();elseif($uri==='/souvenirs/create')SouvenirController::form();elseif($uri==='/souvenirs/bulk-delete')SouvenirController::bulkDelete();elseif(preg_match('#^/souvenirs/(\d+)/edit$#',$uri,$m))SouvenirController::form((int)$m[1]);
elseif($uri==='/scanner/attendance')ScannerController::attendancePage();elseif($uri==='/scanner/souvenir')ScannerController::souvenirPage();elseif($uri==='/api/live')\App\Controllers\LiveController::version();elseif($uri==='/api/scanner/attendance')ScannerController::attendanceApi();elseif($uri==='/api/scanner/souvenir')ScannerController::souvenirApi();
elseif($uri==='/reports/attendance')ReportController::attendance();elseif($uri==='/reports/attendance/data')ReportController::attendanceData();elseif($uri==='/reports/souvenir')ReportController::souvenir();elseif($uri==='/reports/souvenir/data')ReportController::souvenirData();elseif($uri==='/reports/attendance/export')ReportController::exportAttendance();elseif($uri==='/reports/souvenir/export')ReportController::exportSouvenir();
elseif($uri==='/health'){header('Content-Type:application/json');try{\App\Database::connection()->query('SELECT 1');echo json_encode(['status'=>'ok','db'=>'ok','time'=>date('c')]);}catch(Throwable $e){http_response_code(503);echo json_encode(['status'=>'error']);}}
else{http_response_code(404);echo '404 Not Found';}
